image: erlendum/golang-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind


stages:          # List of stages for jobs, and their order of execution
  - pre
  - linter
  - image
  - test_build
  - test
  - build
  - extra

# linter-job:
#   stage: pre
#   script:
#     - echo "linter"
  
# image-job:
#   stage: image
#   script:
#     - echo "docker up"
#   needs:
#     - linter-job

test-build-job:      
  stage: test_build
  script:
      - cd backend 
      - go mod init backend
      - go mod tidy
  # needs:
  #   - image-job

unit-test-job:  
  stage: test   
  script:
    - cd backend 
    - go mod init backend
    - go mod tidy
    - cd internal/services/implementation
    - go test client_test.go client.go -v -cover -coverprofile=client.out
    - go test record.go record_test.go -v -cover -coverprofile=record.out
    - go test pet_test.go pet.go -v -cover -coverprofile=pet.out
    - go test doctor.go doctor_test.go -v -cover  -coverprofile=doctor.out
  artifacts:
    paths:
      - backend/internal/services/implementation/client.out
      - backend/internal/services/implementation/record.out
      - backend/internal/services/implementation/pet.out
      - backend/internal/services/implementation/doctor.out
    expire_in: 1 hour
  needs:
    - test-build-job


  
db-test-job:  
  stage: test   
  script:
    - cd backend 
    - go mod init backend
    - go mod tidy
    - cd internal/services/implementation
    - go test recordPostgres_test.go config_for_test.go record.go record_test.go petPostgres_test.go pe
t.go -v -cover -coverprofile=db.out
   artifacts:
    paths:
      - backend/internal/services/implementation/db.out
    expire_in: 1 hour
  needs:
    - test-build-job

build-job:    
  stage: build
  script:
    - cd backend 
    - go mod init backend
    - go mod tidy
    - cd cmd
    - go build main.go
  artifacts:
    paths:
      - backend/cmd/main
    expire_in: 1 hour
  needs:
    - unit-test-job
    - db-test-job



# research-job:   # This job runs in the test stage.
#   stage: extra    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests..."
#   when: manual
#   needs:
#    - build-job

# documentation-job:   # This job runs in the test stage.
#   stage: extra    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests..."
#   when: manual
#   needs:
#     - build-job

