version: "3.9"

services:
  app: 
    image: golang:1.20
    container_name: my-app
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres # адрес хоста базы данных (используется имя сервиса)
      - POSTGRES_USER=dashori
      - POSTGRES_PASSWORD=parasha
    script:
      - cd ../..
      - go mod init backend
      - go mod tidy
      - cd internal/services/implementation
      - go test -v -cover

    ports:
      - 8080:8080

  postgres:
    container_name: postgres_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "dashori"
      POSTGRES_PASSWORD: "parasha"
    ports:
      - "5432:5432"
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d

