version: "3.9"

services:
  app: 
    build: .
    container_name: my-app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres # адрес хоста базы данных (используется имя сервиса)
      - DB_PORT=5432 # порт базы данных
      - DB_USER=dashori
      - DB_PASSWORD=parasha
      - DB_NAME=postgres

    ports:
      - 8080:8080

  postgres:
    container_name: postgres_db
    restart: always
    build: ./
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "dashori"
      POSTGRES_PASSWORD: "parasha"
    ports:
      - "5432:5432"
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d

