version: "3.9"

services:
  postgres:
    container_name: postgres_db
    restart: always
    build: ./
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "dashori"
      POSTGRES_PASSWORD: "parasha"
    ports:
      - "5432:5432"
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d
    command: /bin/sh -c "entrypoint.sh"

